swagger: '2.0'
info:
  title: Library API
  description: Library API - EDC API Workshop
  version: 1.0.0
  contact:
    email: oyron@equinor.com
host: 'localhost:3000'
basePath: /api
schemes:
  - http
tags:
  - name: library
    description: A library of books
paths:
  /books:
    get:
      tags:
        - library
      summary: Return all books
      operationId: getBooks
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
definitions:
  Book:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      author:
        type: string
  BookData:
    type: object
    properties:
      name:
        type: string
      author:
        type: string
externalDocs:
  description: API documentation
  url: 'http://localhost:3000'
