swagger: '2.0'
info:
  description: Library API - EDC API Workshop
  version: 1.0.0
  title: Library API
  contact:
    email: oyron@equinor.com
host: 'localhost:3000'
basePath: /api
tags:
  - name: library
    description: A library of books
schemes:
  - http
paths:
  '/books/{id}':
    get:
      tags:
        - library
      summary: Get book
      description: ''
      operationId: getBook
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Book id
          type: integer
          required: true
      responses:
        '200':
          description: OK
          schema:
            items:
              $ref: '#/definitions/Book'
        '400':
          description: Bad request
        '404':
          description: Not found
          
definitions:
  Book:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      author:
        type: string
  BookData:
    type: object
    properties:
      name:
        type: string
      author:
        type: string
        
externalDocs:
  description: API portal
  url: http://localhost:3000
