openapi: 3.0.0
info:
  description: API Workshop
  version: 1.0.0
  title: API Workshop
  contact:
    email: oyron@equinor.com
  license:
    name: GNU GPLv3
    url: 'https://choosealicense.com/licenses/gpl-3.0/'
servers:
  - url: http://localhost:3000/api
    description: Local runtime
  - url: https://edc-api.azurewebsites.net/api
    description: Azure runtime

paths:
  /books/{id}:
    get:
      tags:
        - book
      summary: Get book
      description: ""
      operationId: getBook
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Book id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          description: Bad request
        '404':
          description: Not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
      required: ["id", "title", "author"]
      
    BookData:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
      required: ["title", "author"]
        